objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      app: ittest
    name: open-liberty-s2i
  spec:
    lookupPolicy:
      local: false
    tags:
    - from:
        kind: DockerImage
        name: docker.io/openliberty/open-liberty-s2i:19.0.0.9
      generation: null
      importPolicy: {}
      name: 19.0.0.9
      referencePolicy:
        type: ''
  status:
    dockerImageRepository: ''
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      app: ittest
    name: ittest
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ''
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: ittest
    name: ittest
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: ittest:19.0.0.9
    postCommit: {}
    resources: {}
    source:
      git:
        uri: ${SOURCE_REPOSITORY_URL}
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: open-liberty-s2i:19.0.0.9
        incremental: true
        env:
        - name: DATABASE
          value: my_data
        - name: DATABASE_SERVICE_HOST
          valueFrom:
            secretKeyRef:
              name: ittest-database-bind
              key: uri
        - name: DATABASE_SERVICE_PORT
          value: '5432'
        - name: MYSQL_SERVICE_PORT
          value: '3306'
        - name: DATABASE_DATASOURCE
          value: MyDS
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: ittest-database-bind
              key: user
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ittest-database-bind
              key: password
        - name: GC_MAX_METASPACE_SIZE
          value: '150'
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: LIBERTY_RUNNABLE_JAR
          value: runtime-openliberty.jar
      type: Source
    triggers:
    - type: GitHub
      github:
        secret: ${GITHUB_WEBHOOK_SECRET}
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}
  status:
    lastVersion: 0
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      app: ittest
    name: ittest
  spec:
    replicas: 1
    selector:
      app: ittest
      deploymentconfig: ittest
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: ittest
          deploymentconfig: ittest
      spec:
        containers:
        - image: ittest:19.0.0.9
          name: ittest
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8778
            protocol: TCP
          resources:
            limits:
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 120
            timeoutSeconds: 3
          env:
          - name: DATABASE
            value: my_data
          - name: DATABASE_SERVICE_HOST
            valueFrom:
              secretKeyRef:
                name: ittest-database-bind
                key: uri
          - name: DATABASE_SERVICE_PORT
            value: '5432'
          - name: MYSQL_SERVICE_PORT
            value: '3306'
          - name: DATABASE_DATASOURCE
            value: MyDS
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: ittest-database-bind
                key: user
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ittest-database-bind
                key: password
          - name: GC_MAX_METASPACE_SIZE
            value: '150'
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: LIBERTY_RUNNABLE_JAR
            value: runtime-openliberty.jar
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ittest
        from:
          kind: ImageStreamTag
          name: ittest:19.0.0.9
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: ittest
    name: ittest
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8778-tcp
      port: 8778
      protocol: TCP
      targetPort: 8778
    selector:
      app: ittest
      deploymentconfig: ittest
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    name: ittest
    labels:
      app: ittest
  spec:
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: ittest
- kind: Secret
  apiVersion: v1
  metadata:
    name: ittest-database-bind
    labels:
      app: ittest
  stringData:
    uri: ittest-database
    database: my_data
    user: dbuser
    password: secret
- apiVersion: image.openshift.io/v1
  generation: 0
  image:
    dockerImageLayers: null
    dockerImageMetadata:
      ContainerConfig: {}
      Created: null
      Id: ''
      apiVersion: '1.0'
      kind: DockerImage
    dockerImageMetadataVersion: '1.0'
    metadata:
      creationTimestamp: null
  kind: ImageStreamTag
  lookupPolicy:
    local: false
  metadata:
    creationTimestamp: null
    labels:
      app: ittest
    name: ittest-database:10
  tag:
    annotations: null
    from:
      kind: DockerImage
      name: 172.30.1.1:5000/openshift/postgresql:10
    generation: null
    importPolicy: {}
    name: '10'
    referencePolicy:
      type: ''
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      app: ittest
    name: ittest-database
  spec:
    replicas: 1
    selector:
      app: ittest
      deploymentconfig: ittest-database
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: ittest
          deploymentconfig: ittest-database
      spec:
        containers:
        - image: 172.30.1.1:5000/openshift/postgresql:10
          name: ittest-database
          ports:
          - containerPort: 5432
            protocol: TCP
          resources:
            limits:
              cpu: '1'
              memory: 512Mi
          volumeMounts:
          - mountPath: /var/lib/pgsql/data
            name: ittest-database-volume-1
          readinessProbe:
            initialDelaySeconds: 5
            exec:
              command:
              - /usr/libexec/check-container
          livenessProbe:
            initialDelaySeconds: 120
            exec:
              command:
              - /usr/libexec/check-container
              - --live
          env:
          - name: POSTGRESQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: ittest-database-bind
                key: database
          - name: POSTGRESQL_USER
            valueFrom:
              secretKeyRef:
                name: ittest-database-bind
                key: user
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ittest-database-bind
                key: password
        volumes:
        - emptyDir: {}
          name: ittest-database-volume-1
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ittest-database
        from:
          kind: ImageStreamTag
          name: postgresql:10
          namespace: openshift
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: ittest
    name: ittest-database
  spec:
    ports:
    - name: 5432-tcp
      port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      app: ittest
      deploymentconfig: ittest-database
  status:
    loadBalancer: {}
parameters:
- name: SOURCE_REPOSITORY_URL
  description: The source URL for the application
  displayName: Source URL
  value: https://github.com/dummy_org/dummy_repo
  required: true
- name: GITHUB_WEBHOOK_SECRET
  description: The secret used to configure a GitHub webhook
  displayName: GitHub Webhook Secret
  required: true
  from: '[a-zA-Z0-9]{40}'
  generate: expression
apiVersion: template.openshift.io/v1
kind: Template
